name: Cypress Tests

on: 
  push:
      branches:
      - Cypress
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install
        run: npm install
      
      - name: Test run
        run: npm test

      - name: Output test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: mochawesome-report